version: "3.7"

services:
  database:
    image: postgres
    container_name: postgres_product-system
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=product_system
      - POSTGRES_DB=product_system
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
